### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by finnickniu** [akash13singh/lstm_anomaly_thesis#3]
Hi, recently, I am confused by whether the training set should include outliers, I saw you said you trained the normal time series data, I do not know the meaning of normal.

Please reply to me when you saw it,
Many Thanks,
Finn

**Comment by akash13singh** [comment]
Hi Finn,

by normal I mean the observation which are not anomalies. All expected patterns/behaviours in data are normal observation. Observation(s) which show unusual behaviour are anomalies. The datasets I used had labelled anomalies. I removed these while training the prediction model. This is because we want the model to be learn the normal patterns. So that when the model encounters an anomaly, it makes a high prediction error, as the model has not been trained on such data. These high prediction errors on anomalies are then exploited to act as anomaly indicators.  

I hope this explanation clears your doubt.
