### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by vrr187** [akash13singh/lstm_anomaly_thesis#5]
Hello Akash. I've some questions for you...

1) Is it possible to run this LSTM code with multi input parameters?
2) The original parameters configuration is the one which have the best results?
3) I don't understand why it returns me 2 very seimilar graphs everytime I run it in PyCharm, could u explain me?
4) On this application it's only possible to run this project by manually labeling the anomalies in the dataset?

Thanks!

**Comment by akash13singh** [comment]
Hi,

Please find below my answers:
1.  No. Some modifications will be required to run this code on multidimensional input ( parameters?).
2. Yes for the given datasets and model architecture the parameters have been optimized.
3. I will need more context in order to answer this: what input, which model etc.
4. Yes, currently we do require a few labelled anomalies. The prediction part will work. However to set the threshold for anomaly detection one needs a few labelled anomalies.
